### ISSUE TITLE
Sign text not rendering

### ISSUE THREAD

**Issue by DarkAndBlue** [tr7zw/Exordium#92] opened 2023-07-31 11:54 UTC
The text of signs isn't rendering on Minecraft version 1.20.1.

With exordium installed:
![2023-07-31_13 49 46](https://github.com/tr7zw/Exordium/assets/13067258/3b75e053-e50a-4999-9238-00d23d0b3d24)

Without exordium installed:
![2023-07-31_13 50 36](https://github.com/tr7zw/Exordium/assets/13067258/af64bc6c-36f4-46f6-b6c0-fe7dbe83177f)

Mods:
- Sodium 0.4.10
- Exordium 1.20.1 - 1.1.3
- Fabric API 0.86.1

**Comment by DarkAndBlue** [comment] 2023-07-31 11:55
Loading Exordium without Sodium has the same effect.

**Comment by tr7zw** [comment] 2023-07-31 11:57
> Note: this is more of a temporary release, since it's basically a straight port of the 1.19.4 version. Adds known issues with mods like Enhanced Block Entities. Tested with ImmediatelyFast.

**Comment by DarkAndBlue** [comment] 2023-07-31 12:06
> > Note: this is more of a temporary release, since it's basically a straight port of the 1.19.4 version. Adds known issues with mods like Enhanced Block Entities. Tested with ImmediatelyFast.

What does that mean? Is the issue already known or do you think im using Enhanced Blcok Entities or ImmediatelyFast? Or do you want me to use Enhanced Block Entities or ImmediatelyFast?

Or do you want me to not report this bug as it is marked as "temporary release"?

**Comment by tr7zw** [comment] 2023-07-31 12:10
I mean with that, I know that this release is not perfect/has issues, especially with other mods. I don't have the time right now to make it proper, but people kept asking for "Exordium 1.20 when?". I know it works with just Sodium(at least it was tested with Sodium and ImmediatelyFast), so I assume you have something else in there causing issues. Either way, you can just turn off Sign buffering in the settings to fix it.

**Comment by DarkAndBlue** [comment] 2023-07-31 12:21
Yes I wanted to write that too with disabling sign buffering to temporarily disable fix the bug.

And Im only using the mods I listed above.

Also please don't feel stressed or pressured by this issue.
I only wanted to create this issue as I noticed it today and the version was new released and I thought you might need feedback/issues.

**Comment by tr7zw** [comment] 2023-07-31 12:22
Hm, in that case, it could be interesting if adding ImmediatelyFast fixes it? Cause I had people test with Sodium before, without any issues.

**Comment by WithLithum** [comment] 2023-08-02 03:39
> Hm, in that case, it could be interesting if adding ImmediatelyFast fixes it? Cause I had people test with Sodium before, without any issues.

I encountered this issue some days ago, and tested with following circumstances iirc:

- With Sodium, Enhanced Block Entities, Exordium, ImmediatelyFast, EntityCulling = Yes
- With Sodium, Enhanced Block Entities, Exordium, ImmediatelyFast = Yes
- With Sodium, Exordium, ImmediatelyFast = Yes
- With Sodium, ImmediatelyFast = No

**Comment by tr7zw** [comment] 2023-08-02 12:50
I mean, right now it crashes with Enhanced Block Entities, unless you turn off the buffering?

**Comment by WithLithum** [comment] 2023-08-04 12:52
Configuration was not changed in any of the mods above I have listed.

**Comment by tr7zw** [comment] 2023-08-04 13:19
Then your game should just crash once a sign tries to render.

**Comment by WithLithum** [comment] 2023-08-05 03:04
Just re-tested with only Fabric API `0.86.1+1.20.1`, Enhanced Block Entities `0.9+1.20` and Exordium `1.1.3.1-mc1.20.1`, and sign text renders with no issues. The game did not crash.

OS: KUbuntu 23.04
GPU: AMD core graphics card
Resource Packs: None

`exordium.json`:
```json
{
  "configVersion": 2,
  "enableSignBuffering": true,
  "targetFPSNameTags": 60,
  "enableNametagScreenBuffering": false,
  "chatSettings": {
    "enabled": true,
    "maxFps": 20,
    "forceBlend": false,
    "forceUpdates": false
  },
...
}
```

**Comment by WithLithum** [comment] 2023-08-05 03:08
The "blank sign" issue is still present with the same config as above except without Enhanced Block Entities AND with Sodium installed.

**Comment by sydist** [comment] 2023-08-06 21:21
isn't this a duplicate of #27

**Comment by tr7zw** [comment] 2023-08-06 21:22
No. This is just about 1.20 and since the release is not a "done" 1.20 release, its buggy. But for both the fix is the same, just turn off the buffering.

**Comment by sydist** [comment] 2023-08-06 21:37
Im also running into a similar issue with "Enable Nametags Buffering", it makes nametags invisible, should I open a seperate issue?
it could be the same cause as this one.

**Comment by tr7zw** [comment] 2023-08-06 21:38
No, like I said, this is not a proper release, and these issues won't be worked on for now. Also, the nametag stuff might probably get removed instead of fixed.

**Comment by dophire** [comment] 2023-08-16 18:16
Disable sign buffering.

**Comment by andreasdc** [comment] 2023-08-16 21:34
> No, like I said, this is not a proper release, and these issues won't be worked on for now. Also, the nametag stuff might probably get removed instead of fixed.

It would be epic to have nametag buffering back, can you imagine if Exordium will give even better fps boost? Maybe also buffering hand/item? Everybody has text and hand on their screen almost all the time.

**Comment by forkiesassds** [comment] 2023-08-21 23:47
This issue doesn't happen when there is text on both sides on the sign, which is a 1.20+ feature. I assume Exordium doesn't properly handle 1.20+ signs and thus causes it to fail rendering entirely. For now you will have to put text on the other side of the sign.

**Comment by tr7zw** [comment] 2023-08-22 11:41
I tested with text on both sides, worst case some check messes up and cancels rendering when there is text Only on one side.

**Comment by tr7zw** [comment] 2023-08-22 14:37
> This issue doesn't happen when there is text on both sides on the sign, which is a 1.20 feature. I assume Exordium doesn't properly handle 1.20 signs and thus causes it to fail rendering entirely. For now you will have to put text on the other side of the sign.

50 points to you:
It skipped everything when both sides were empty, but the logic broke down when one side had text only. Also, an internal cache was not filled(probably causing a re-render each frame, which defeats the entire point). As said in the release notes, this 1.20 version is a "Better than nothing" WIP release, just don't have the irl time to test/debug/implement all the things right now.

**Closed** 2023-08-22 14:38 UTC
