### ISSUE TITLE
[Bug] Sign buffering removes text and glow

### ISSUE THREAD

**Issue by ExperiBass** [tr7zw/Exordium#27] opened 2022-10-04 21:57 UTC
When sign buffering is turned on, the text doesn't render, but the glow layer seems to render randomly.

With sign buffering on  
![2022-Oct-04-15-36-36](https://user-images.githubusercontent.com/33764485/193937649-b7dbec93-1c33-4d27-92ee-5b5788f4a939.png)

With sign buffering off  
![2022-Oct-04-15-37-01](https://user-images.githubusercontent.com/33764485/193937716-1df2f5d5-fc9a-43d8-9dc9-657a0dc55d11.png)

**Comment by tr7zw** [comment] 2022-10-04 21:58
Huh. Which other graphics mods are installed, and how are the signs loaded? (log in next to them/walking them into view distance?)

**Comment by ExperiBass** [comment] 2022-10-04 23:30
> Which other graphics mods are installed

[Better Biome Blend](https://modrinth.com/mod/Rs6c7WyL)  
[Clear Skies](https://modrinth.com/mod/xNK6XfRv)  
[Continuity](https://modrinth.com/mod/1IjD5062)  
[Cull Leaves](https://modrinth.com/mod/GNxdLCoP)  
[EntityCulling](https://modrinth.com/mod/NNAgCjsB)  
[Extended Clouds](https://modrinth.com/mod/SRvY3a39)  
[Iris Shaders](https://modrinth.com/mod/YL57xq9U)  
[Make Bubbles Pop](https://modrinth.com/mod/gPCdW0Wr)  
[Model Gap Fix](https://modrinth.com/mod/QdG47OkI)  
[No More Purple](https://modrinth.com/mod/32J251wv)  
[Phosphor](https://modrinth.com/mod/hEOCdOgW)  
[Raised](https://modrinth.com/mod/nCQRBEiR)  
[Reese's Sodium Options](https://modrinth.com/mod/Bh37bMuy)  
[Show Me Your Skin!](https://modrinth.com/mod/bD7YqcA3)   
[Sodium Extra](https://modrinth.com/mod/PtjYWJkn)  
[Sodium](https://modrinth.com/mod/AANobbMI)  


> and how are the signs loaded? (log in next to them/walking them into view distance?) Also singleplayer or multiplayer?

It appears to be both when logging in and when walking towards them. It happens on both single and multiplayer.

Further testing revealed its actually just the glow layer, and it also leaves random pixels of the text.
![2022-Oct-04-19-28-25](https://user-images.githubusercontent.com/33764485/193948835-b7463f44-2bf0-4b77-827e-ba71254fef74.png)

**Comment by tr7zw** [comment] 2022-10-04 23:43
Hmm this is odd. So far have no one else reproducing this.  And the glitched text looks like something messed up the render pipeline before the signs get rendered out.  Once we figure out which exact mod/situation causes this, then I can try mitigating the issue.

**Comment by sydist** [comment] 2023-08-06 21:20
This same thing is happening to me, except the sign text doesn't show at all, even when it's glowing
Still happens even with just Fabric API and Exordium

**Comment by tr7zw** [comment] 2023-08-06 21:21
Assuming you are on 1.20, please use #92.

**Comment by tr7zw** [comment] 2023-08-06 21:23
Actually gonna close this one, since there are no reports like this since then, and a lot has changed.

**Closed by tr7zw** 2023-08-06 21:23 UTC
