### ISSUE TITLE
Invisible hotbar

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/Exordium#66] opened 2023-05-28 17:36 UTC
Nice to see the update. :) The hotbar is invisible/visible on for split second during updates. The refreshes only during updates are still capped? Because I don't think I can smooth through chat smoothly. I see big performance improvement. :)

**Comment by tr7zw** [comment] 2023-05-28 17:37
> The hotbar is invisible/visible on for split second during updates.

I'll need the modlist for that. Not happening with my setup

And yes, if something updates 20 times a second and the setting are set to cap it to 5fps, then it will only update 5 times per second.

**Comment by andreasdc** [comment] 2023-05-28 17:43
> > The hotbar is invisible/visible on for split second during updates.
> 
> I'll need the modlist for that. Not happening with my setup
> 
> And yes, if something updates 20 times a second and the setting are set to cap it to 5fps, then it will only update 5 times per second.

So it's safe to set higher cap?
ImmediatelyFast is the issue.
Config
`{
  "REGULAR_INFO": "----- Regular config values below -----",
  "font_atlas_resizing": true,
  "map_atlas_generation": true,
  "hud_batching": true,
  "fast_text_lookup": true,
  "fast_buffer_upload": true,
  "COSMETIC_INFO": "----- Cosmetic only config values below (Does not optimize anything) -----",
  "dont_add_info_into_debug_hud": false,
  "EXPERIMENTAL_INFO": "----- Experimental config values below (Rendering glitches may occur) -----",
  "experimental_item_hud_batching": true,
  "experimental_disable_error_checking": true,
  "experimental_disable_resource_pack_conflict_handling": false,
  "DEBUG_INFO": "----- Debug only config values below (Do not touch) -----",
  "debug_only_and_not_recommended_disable_universal_batching": false,
  "debug_only_and_not_recommended_disable_mod_conflict_handling": false,
  "debug_only_and_not_recommended_disable_os_conflict_handling": false
}`

**Comment by tr7zw** [comment] 2023-05-28 17:44
Are you sure you downloaded the latest release? Sounds a lot like 2-3 commits old, before I fixed the ImmediatlyFast support.

**Comment by andreasdc** [comment] 2023-05-28 17:45
Latest release of what?

**Comment by tr7zw** [comment] 2023-05-28 17:45
https://modrinth.com/mod/exordium/version/1.1.0-1.19.4

**Comment by andreasdc** [comment] 2023-05-28 17:45
> https://modrinth.com/mod/exordium/version/1.1.0-1.19.4

I took it from github releases

**Comment by tr7zw** [comment] 2023-05-28 17:48
Thats the same jar. It does work with `ImmediatelyFast-1.1.12+1.19.4.jar`.

**Comment by andreasdc** [comment] 2023-05-28 17:48
I have ImmediatelyFast-1.1.13.jar

**Comment by tr7zw** [comment] 2023-05-28 17:48
Well, thats not released, so I didn't test with it.

**Comment by andreasdc** [comment] 2023-05-28 17:49
Sure no problem, so is it safe to set higher fps cap if gui refreshes only on updates?

**Comment by tr7zw** [comment] 2023-05-28 17:50
![grafik](https://github.com/tr7zw/Exordium/assets/5133936/c0add66d-8a58-4a91-aea7-e0ec61c90835)
Thats what the setting is there for.

**Comment by andreasdc** [comment] 2023-05-28 17:50
Which setting?

**Comment by tr7zw** [comment] 2023-05-28 17:52
![grafik](https://github.com/tr7zw/Exordium/assets/5133936/19292b77-9f2d-40f1-af1c-d9af69bd164e)

**Comment by andreasdc** [comment] 2023-05-28 17:57
So it's safe to set it higher? It doesn't refresh faster it just the limit?

**Comment by tr7zw** [comment] 2023-05-28 17:58
Yes. It's basically a limit, how often that UI part is allowed to request an update.

**Comment by tr7zw** [comment] 2023-05-28 17:59
You could also turn on the "Force Chat Updates" to get it to refresh at the fps limit even without changes, or just turn off Buffer Chat, then it renders like vanilla.

**Comment by andreasdc** [comment] 2023-05-28 18:01
Perfect. ❤️ Will you fix it with the latest IF?

**Comment by tr7zw** [comment] 2023-05-28 18:01
Probably when its out. For now, you can just diable the Hotbar.

**Comment by andreasdc** [comment] 2023-05-28 18:02
I've built it by my own that's how I got the jar.

**Comment by tr7zw** [comment] 2023-05-28 18:03
Yea, but right now thats pre release having an issue with a pre release. Not worth looking into. Once IF 1.1.13 is out and the issue persists, then I'll look into whats going wrong.

**Comment by HyperSoop** [comment] 2023-05-29 05:29
This issue is caused by IF's hotbar item batching feature, which since 1.1.13 is enabled by default. You can disable it in its configuration file.

**Comment by andreasdc** [comment] 2023-05-29 14:29
> This issue is caused by IF's hotbar item batching feature, which since 1.1.13 is enabled by default. You can disable it in its configuration file.

Yes but it's better to have it enabled, when the bug is fixed of course.

**Comment by Alexander020304** [comment] 2023-06-02 18:22
This problem is still present in 1.1.1

**Comment by tr7zw** [comment] 2023-06-02 18:22
Like I mentioned above, not looking into this since it's not a released feature from what I understand.

**Comment by andreasdc** [comment] 2023-06-02 18:24
> This problem is still present in 1.1.1

Did you test the latest commit of IF?

**Comment by tr7zw** [comment] 2023-06-02 18:24
> Did you test the latest commit of IF?

Again, I'm not testing dev builds. I have the latest IF from CurseForge in my client, and it works. Thats it.

**Comment by andreasdc** [comment] 2023-06-02 18:25
> > Did you test the latest commit of IF?
> 
> Again, I'm not testing dev builds. I have the latest IF from CurseForge in my client, and it works. Thats it.

I'm asking @Alexander020304, but it would be nice to get it fixed already and be ready for IF release :D

**Comment by tr7zw** [comment] 2023-06-02 18:29
I'll look into it with RK_01 once it gets there. But right now don't have the time and interest to look into making unfinished and unreleased stuff compatible(especially since this won't affect anyone but a handful of people, and they did it to themselves^^).

**Comment by andreasdc** [comment] 2023-06-02 18:40
> I'll look into it with RK_01 once it gets there. But right now don't have the time and interest to look into making unfinished and unreleased stuff compatible(especially since this won't affect anyone but a handful of people, and they did it to themselves^^).

Not a huge issue especially with your latest update 🚀 By the way when more or less you plan to batch bossbar or tablist? Also will you take look into rendering hand/item in hand too?

**Comment by tr7zw** [comment] 2023-06-02 18:43
Yes the missing parts(boss bar, tab and audio subtitles) I will add. Some stuff like titles is just not worth it, and the item in hand gets real time shadow changes n stuff, that wouldn't work.

**Comment by andreasdc** [comment] 2023-06-02 18:44
Potentially there is actionbar and item names too

**Comment by tr7zw** [comment] 2023-06-02 18:47
> Potentially there is actionbar and item names too

What did I just say xD?

**Comment by Alexander020304** [comment] 2023-06-02 18:48
I did all the testing on the currently builds of if
I can test the dev build if you would like.

**Comment by tr7zw** [comment] 2023-06-02 18:49
![grafik](https://github.com/tr7zw/Exordium/assets/5133936/5c4715db-a69d-40c8-b405-cc8d6756aa7c)
Like I said, I have the current release in my client on default settings, and it doesn't flicker.

**Comment by Alexander020304** [comment] 2023-06-02 18:50
i will check the settings  then

**Comment by Alexander020304** [comment] 2023-06-02 18:59
even will stock settings this still happens;
![2023-06-02_14 58 23](https://github.com/tr7zw/Exordium/assets/96150724/a178af76-bdbc-425a-b1f3-037665148d2d)
the star is broken

**Comment by andreasdc** [comment] 2023-06-02 19:00
> > Potentially there is actionbar and item names too
> 
> What did I just say xD?

Nothing about that I guess

**Comment by andreasdc** [comment] 2023-06-02 19:01
> even will stock settings this still happens; ![2023-06-02_14 58 23](https://user-images.githubusercontent.com/96150724/242969201-a178af76-bdbc-425a-b1f3-037665148d2d.png) the star is broken

What is wrong here btw?

**Comment by Alexander020304** [comment] 2023-06-02 19:02
all enchanted items are broken in the hotbar

**Comment by tr7zw** [comment] 2023-06-02 19:17
Ah I think I forgot to include the enchant check to refresh the hotbar while enchanted items are inside. That should be its own issue, nothing to do with IF.

**Comment by andreasdc** [comment] 2023-06-08 01:46
The latest IF released https://github.com/RaphiMC/ImmediatelyFast/releases

**Comment by LichLord91** [comment] 2023-06-09 03:50
Hotbar invisible for me too have to turn off buffering to work>

Mods
![image](https://github.com/tr7zw/Exordium/assets/8435580/5ab10b38-1c12-4fa9-886f-7f7a4287d8d6)

**Comment by andreasdc** [comment] 2023-06-09 04:06
Latest IF is not supported yet, you can disable hud_batching in the config file until it is fixed.

**Comment by tr7zw** [comment] 2023-06-12 16:53
Fixed in 1.1.2

**Closed by tr7zw** 2023-06-12 16:53 UTC
Labels: bug, wontfix, fabric, Mod-Compatibility

**Comment by WxAaRoNxW** [comment] 2025-02-28 18:18
in ImmediatelyFast with `"experimental_universal_hud_batching": true`, flickering hotbar occurs.

MC: 1.21.1
Exordium: 1.4.1-1.21 Fabric
ImmediatelFast: 1.3.5+1.21.1 Fabric
