### ISSUE TITLE
[Forge] Iron's Spells 'n Spellbooks crashes

### ISSUE THREAD

**Issue by Ninccino** [tr7zw/Exordium#107] opened 2023-09-09 00:44 UTC
**Exordium & Iron's Spells 'n Spellbooks result in:**
_java.lang.RuntimeException: Unable to load Exordium Shader_

[The crash does not appear to be mod or modloader version dependent.](https://mclo.gs/uM3iPXe) <- Crash report)

**Mods:**
- [Exordium](https://legacy.curseforge.com/minecraft/mc-mods/exordium)
- [Iron's Spells 'n Spellbooks](https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
- [Mixin In Heaven](https://legacy.curseforge.com/minecraft/mc-mods/mixin-in-heaven)
- [playerAnimator](https://legacy.curseforge.com/minecraft/mc-mods/playeranimator)

**Comment by tr7zw** [comment] 2023-09-09 12:06
It's not finding a file from the Exordium jar ``Caused by: java.io.FileNotFoundException: minecraft:shaders/core/position_multi_tex.json``. Not sure how this could happen, but I guess at least my code caught it. Maybe it causes a resource load before Forge has hooked the Exordium resources? Will have to test around.

**Comment by Ninccino** [comment] 2023-09-09 21:55
_I used the CurseForge launcher for testing and it didn't install all the _dependencies_ of Iron's Spells 'n Spellbooks._

**However:**
After a bit more testing, it seems like Exordium hijacks any crash related to missing dependencies.

**For example:** [Exordium](https://modrinth.com/mod/exordium) & [YUNG's Better Mineshafts](https://modrinth.com/mod/yungs-better-mineshafts) results in the same crash because it doesn't have [YUNG's API](https://modrinth.com/mod/yungs-api).
_Fabric catches the lacking dependency, while either Forge blames Exordium/Exordium takes the blame._

**Comment by tr7zw** [comment] 2023-09-09 22:36
I also did test with the Curse Launcher, as I said, it looks like something tries to cause a load before Exordiums resources are loaded. Potentially not an issue trying go ignore that exception.

**Comment by tr7zw** [comment] 2024-09-27 19:38
Closing all forge issues as the forge version never worked and theres no plans for a new one.

**Closed by tr7zw** 2024-09-27 19:38 UTC
