### ISSUE TITLE
[1.18.2] Exordium display problem with fps reducer (its not showing the correct fps number)

### ISSUE THREAD

**Issue by quentin452** [tr7zw/Exordium#31] opened 2022-10-15 16:46 UTC
mods lists needed : 

exordium-fabric-1.0.1-mc1.18.2
FpsReducer2-fabric-1.18.2-2.0

screenshot : 

![Capture d’écran_2022-10-15_18-46-00](https://user-images.githubusercontent.com/42176772/195998234-19616e7a-25fa-4e99-90bf-bf831f1f4abe.png)

**Comment by tr7zw** [comment] 2022-10-15 16:48
Probably the same issue as #30 . Nothing I can fix and they need to count the fps at a different/correct place.

**Comment by quentin452** [comment] 2022-10-15 16:49
i found an alternative , and its work https://www.curseforge.com/minecraft/mc-mods/fpsdisplay

**Comment by tr7zw** [comment] 2022-10-15 16:51
The issue is: the mod counts how often the hud renders and takes that as fps. This mods goal is to reduce how often the hud renders. Result, that number is wrong. Mc provides the correct fps, or they can hook the render logic to calculate the fps. So this isn't a bug on my end, since the mod does exactly what it should.

**Comment by tr7zw** [comment] 2023-02-07 13:00
Closing the issue, since it's not an issue with this mod.

**Closed by tr7zw** 2023-02-07 13:00 UTC
Labels: bug, invalid, fabric, Mod-Compatibility
