### ISSUE TITLE
Sign text is invisible when using this mod alongside Iris

### ISSUE THREAD

**Issue by ChristopherHaws** [tr7zw/Exordium#37] opened 2022-11-09 03:18 UTC
When using this mod with sodium, fabric api, and iris installed and using complementary shaders v4.6, this mod causes the text on signs to become invisible.

Here are my logs:
https://mclo.gs/hi4SGBp

Here is an image of this happening:
![image](https://user-images.githubusercontent.com/5934505/200729113-43ae723a-4452-4ce7-a991-85cc6659ceda.png)

**Comment by tr7zw** [comment] 2022-11-13 21:10
Ah, had this issue mentally filed under the weird issue when sometimes the text is not rendered at all. But making the sign see-through is a new one. Will look into it.

**Comment by tr7zw** [comment] 2022-11-13 21:27
Hm, can not reproduce.
![grafik](https://user-images.githubusercontent.com/5133936/201545356-b31fcdcd-7d6e-4f98-8836-a8547e8d229e.png)

**Comment by ChristopherHaws** [comment] 2022-11-13 23:07
I will see if I can repro it again and provide more info. It might be something hidden behind a config tweak and not vanilla config. I will get back to you as soon as I get a chance to play around with it. :)

**Comment by E8LL4IQuU** [comment] 2023-08-26 08:32
Text on signs is invisible...

Java v.17.0.3

Config 1: 1.20.1 Fabric v0.14.22
mods:
exordium-fabric-1.1.3.1-mc1.20.1
fabric-api-0.87.0+1.20.1

Config 2: 1.20.1 Quilt v0.19.3
mods:
exordium-fabric-1.1.3.1-mc1.20.1
qfapi-7.1.2_qsl-6.1.1_
fapi-0.87.0_mc-1.20.1

[quilt.log](https://github.com/tr7zw/Exordium/files/12444875/quilt.log)

Config: 
Tlauncher legacy
GPU: RX 570 2048SP
DDR4 16gb
CPU: i5 6400
windows 22h2

**Comment by tr7zw** [comment] 2023-09-06 20:32
I'll close this since there haven't been any reports since.

**Closed by tr7zw** 2023-09-06 20:32 UTC
